### PR TITLE
Update sailfish-qrshare-es.ts

### PR DESCRIPTION
**Pull request by carlosgonz0**

### CODE REVIEW

**Comment by monich** [comment]
Is "Generar código QR" incorrect or are there other reasons to strip the verb?

**Comment by carlosgonz0** [comment]
I did it this way to ALIGN it with the other sentences, SHARE is an extra word, the whole page where these sentences are is to SHARE  automatically.

**Comment by carlosgonz0** [comment]
So " QR code " may be better.

**Comment by monich** [comment]
Kind of makes sense, then other translations should be adjusted as well... Let me think about.

**Comment by carlosgonz0** [comment]
> Kind of makes sense, then other translations should be adjusted as well... Let me think about.

Yeap

**Comment by carlosgonz0** [comment]
Expired.

**Pull request closed without merging**
